name: Cleanup Old Images

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours UTC
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://attractiveness-checker.onrender.com/cleanup
